version: '3.9'

services:
  php-fpm:
    image: webdevops/php-nginx:8.0-alpine
    restart: always
    ports:
      - 81:80
    networks:
      custom_network:
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - WEB_DOCUMENT_INDEX=index.php
    volumes:
      - ./code/symfony-fpm:/app

  php-swoole-symfony:
    build:
      context: ./code/symfony-swoole
      dockerfile: Dockerfile
    restart: always
    ports:
      - 82:9501
    networks:
      custom_network:
    volumes:
      - ./code/symfony-swoole:/var/www
    command: ["php", "/var/www/bin/console", "swoole:server:run", "--api"]

  php-swoole-laravel:
    build:
      context: ./code/laravel-octane
      dockerfile: Dockerfile
    restart: always
    ports:
      - 83:8000
    networks:
      custom_network:
    volumes:
      - ./code/laravel-octane:/var/www
    command: ["php", "artisan", "octane:start", "--port=8000", "--host=0.0.0.0"]

#  db:
#    image: mysql:8.0
#    restart: always
#    networks:
#      custom_network:
#    environment:
#      MYSQL_DATABASE: test
#      MYSQL_USER: test
#      MYSQL_PASSWORD: test
#      MYSQL_ROOT_PASSWORD: test
#    volumes:
#      - db:/var/lib/mysql

#volumes:
#  db:

networks:
  custom_network: