apiVersion: apps/v1
kind: Deployment
metadata:
  name: symfony-swoole-deployment
spec:
  selector:
    matchLabels:
      app: symfony-swoole
  replicas: 1
  template:
    metadata:
      labels:
        app: symfony-swoole
    spec:
      containers:
      - name: symfony-swoole
        image: symfony-swoole-image:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
