apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-swoole-deployment
spec:
  selector:
    matchLabels:
      app: laravel-swoole
  replicas: 1
  template:
    metadata:
      labels:
        app: laravel-swoole
    spec:
      containers:
      - name: laravel-swoole
        image: laravel-swoole-image:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
