apiVersion: apps/v1
kind: Deployment
metadata:
  name: symfony-fpm-deployment
spec:
  selector:
    matchLabels:
      app: symfony-fpm
  replicas: 1
  template:
    metadata:
      labels:
        app: symfony-fpm
    spec:
      containers:
      - name: symfony-fpm
        image: symfony-fpm-image:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
